### ISSUE TITLE
Is the setup.py requirement for ZODB 5.6 a hard requirement

### ISSUE THREAD

**Issue by darryldixon** [zopefoundation/tempstorage#19]
Hi @dataflake 

The latest fixes from tempstorage 5.1 to 5.2 also bumped ZODB requirement in setup.py from >=5.0 to >=5.6. Is this actually a concrete requirement of the current codebase, or instead a best practices/current state of the art recommendation? Do the changes in tempstorage 5.2 break compatibility with ZODB 5.5.1 / require features of ZODB 5.6?

**Comment by dataflake** [comment]
It is a requirement due to API changes in ZODB 5.6.
