### ISSUE TITLE
loadBefore raises KeyError instead of POSKeyError?

### ISSUE THREAD

**Issue by jaroel** [zopefoundation/tempstorage#5]
I noticed that TemporaryStorage raises KeyError in loadBefore: 
https://github.com/zopefoundation/tempstorage/blob/master/src/tempstorage/TemporaryStorage.py#L187

But FileStorage raises POSKeyError for the same purpose (AFAIK): https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/FileStorage/FileStorage.py#L562

Shouldn't the KeyError in TemporaryStorage be a POSKeyError as well?

The thing is that when using collective.recipe.plonesite with a ZEO setup and a temp_folder on the zeoserver I see the following traceback:

```
2017-09-19T00:09:15 Bad request, 'loadBefore'
Traceback (most recent call last):
  File "/Users/roel/.buildout/eggs/ZEO-5.1.0-py2.7.egg/ZEO/asyncio/server.py", line 102, in message_received
    result = getattr(self.zeo_storage, name)(*args)
  File "/Users/roel/.buildout/eggs/ZEO-5.1.0-py2.7.egg/ZEO/StorageServer.py", line 254, in loadBefore
    return self.storage.loadBefore(oid, tid)
  File "/Users/roel/.buildout/eggs/tempstorage-4.0-py2.7.egg/tempstorage/TemporaryStorage.py", line 187, in loadBefore
    raise KeyError(oid)
KeyError: '\x00\x00\x00\x00\x00\x00\x00\x00'
```
This doesn't occur when I locally change the KeyError to POSKeyError.

**Comment by hannosch** [comment]
Raising a POSKeyError would make sense to me. Could you provide a PR?

**Comment by jaroel** [comment]
@hannosch there you go. Do I need to sign some kind of contributor agreement?

**Comment by hannosch** [comment]
@jaroel I don't think this one-liner triggers copyright protection, so I went ahead and merged it.

In theory you could sign the agreement, documented at http://docs.zope.org/developer/becoming-a-committer.html - but unfortunately foundation.zope.org no longer works, so I don't know where to get the agreement from anymore.

**Comment by jaroel** [comment]
Should be fine. Please assume copyright transferred if needed.

**Comment by mgedmin** [comment]
I've found a copy of the agreement PDF on my old disk in case you want to formalize this: https://github.com/zopefoundation/developer_docs/issues/1#issuecomment-330521145
