### ISSUE TITLE
Tests are broken on TravisCI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/tempstorage#9]
See https://travis-ci.org/zopefoundation/tempstorage.

Probably we only need a newer PyPy version.

**Comment by jugmac00** [comment]
Could you elaborate a bit why we support pypy for a few packages and whether there is really somebody out there using them?

Given we are only a handful of maintainers, pypy seems to be a niche product and Travis does not make it easy to keep up with pypy releases, I'd suggest to drop pypy support completely.

Gonna create a pull reauest later (when there is some time).

**Comment by icemac** [comment]
`tempstorage` does not depend on `Zope` (which does not support PyPy because `RestrictedPython` cannot support it), so it can be used with PyPy. I think it is nice to support PyPy if possible because especially ZODB based applications could profit from its just in time compilation.
